baseURL = 'https://hallgerd.com/'
languageCode = 'en-us'
title = 'Project Hallgerd'
theme = "smol"

# Parameters
[params]
    subtitle = "Welcome."
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "easyrpg"
        name = "EasyRPG"
        url = "/play/index.html"
        weight = 3

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/hallger"
        weight = 1

    [[menu.footer]]
        name = "Email"
        url = "mailto:hall@hallgerd.com"
        weight = 2
